import type { Metadata } from 'next'
import { Outfit, } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar.client'
import Footer from './components/Footer'
import { ToastProvider } from '@/context/BookingCreatedContext'

const inter = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        {/* <SessionWrapper session={session}> */}
        <ToastProvider>
          <body className={`${inter.className} min-h-screen`}>
              <Navbar />
              {children}
              <Footer />
          </body>
        </ToastProvider>
          
        {/* </SessionWrapper> */}
      </html>
  )
}
