import type { Metadata } from 'next'
import { Outfit, Red_Hat_Display } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar.client'
import Footer from './components/Footer'
import SessionWrapper from "./components/SessionWrapper"
import { getServerSession } from 'next-auth'

const inter = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
      <html lang="en">
        {/* <SessionWrapper session={session}> */}
          <body className={`${inter.className}`}>
              <Navbar />
              {children}
              <Footer />
          </body>
        {/* </SessionWrapper> */}
      </html>
  )
}
